export const ActionTypes = {
    GET_ALL_PRODUCT: "GEt_ALL_PRODUCT",
    PRODUCT_ERROR: "PRODUCT_ERROR",
    GET_ALL_USER: "GEt_ALL_USER",
    USER_ERROR: "USER_ERROR",
    GET_USER: "GET_USER",
    GET_CART_BY_USER: "GET_CARTE_BY_USER",
    CARTE_ERROR: "CARTE_ERROR",
    GET_ONE_PRODUCT: "GET_ONE_PRODUCT",

}